POINT_NORMALIZATION = 36.4 #normalize by point change in round that yields std.dev of 1

#### REPLAY BUFFER PARAMETERS FOR DQN
ACTION_REPLAY_BUFFER_SIZE = 250000 #equivalent of ~350 games
BET_REPLAY_BUFFER_SIZE    = 35000
EVAL_REPLAY_BUFFER_SIZE   = 65000

#### RETRAINING
RETRAIN_BATCH_SIZE = 676
RETRAIN_EPOCHS = 1
REG_CONST = 0.0001
LEARNING_RATE = 0.001
MOMENTUM = 0.9
TRAINING_LOOPS = 10

#### EVAL AND BET TRAINING
NUM_NEW_TRANSITIONS_BEFORE_EVAL_BET_TRAIN = 32000
EVAL_TRAIN_EPOCHS = 128
EVAL_TRAIN_BATCH_SIZE = 256
BET_TRAIN_EPOCHS = 128
BET_TRAIN_BATCH_SIZE = 256

#### A3C ALGORITHM PARAMETERS
A3C_NUM_GAMES_PER_WORKER = 1
A3C_NUM_WORKERS = 1
A3C_GLOBAL_NET_UPDATE_EVAL_FREQ = 1
